//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicheskaya_8.DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Specialized;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class AccountTable : INotifyPropertyChanged      //класс счёта клиента
    {
        private string id;
        private string deposit;
        private string nedeposit;
        public string Id
        {
            get => id;
            set
            {
                id = value;
                OnPropetryChanger("Id");
            }
        }
        public string Deposit
        {
            get => deposit; 
            set
            {
                deposit = value;
                OnPropetryChanger("Deposit");
            }
        }
        public string Nedeposit 
        {
            get => nedeposit; 
            set
            { 
                nedeposit = value;
                OnPropetryChanger("Nedeposit");
            }
        }

        public AccountTable() { }

        public event PropertyChangedEventHandler PropertyChanged;       //событие динамического изменения свойств
        public void OnPropetryChanger([CallerMemberName] string prop = "")          //метод динамического изменения свойств
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));
        }
    }
}
