//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practicheskaya_8.DataBase
{
    using Practicheskaya_8.Interface;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;

    public partial class BankTable : IClient, INotifyPropertyChanged    //класс клиента
    {
        private string id;
        private string name;
        private string surname;
        private string otchestvo;
        private string phone;
        private string pasport;
        private string dateTimeChange;
        private string whatDataChanged;
        private string whoChanged;

        public string Id
        {
            get => id;
            set
            {
                id = value;
                OnPropetryChanger("Id");
            }
        }
        public string Name
        {
            get => name;
            set
            {
                name = value;
                OnPropetryChanger("Name");
            }
        }
        public string Surname
        {
            get => surname;
            set
            {
                surname = value;
                OnPropetryChanger("Surname");
            }
        }
        public string Otchestvo
        { 
            get => otchestvo;
            set
            {
                otchestvo = value;
                OnPropetryChanger("Otchestvo");
            }
        }
        public string Phone
        {
            get => phone;
            set
            {
                phone = value;
                OnPropetryChanger("Phone");
            }
        }
        public string Pasport 
        {
            get => pasport;
            set
            {
                pasport = value;
                OnPropetryChanger("Pasport");
            }
        }
        public string DateTimeChange
        {
            get => dateTimeChange;
            set
            {
                dateTimeChange = value;
                OnPropetryChanger("DateTimeChange");
            }
        }
        public string WhatDataChanged 
        {
            get => whatDataChanged;
            set
            {
                whatDataChanged = value;
                OnPropetryChanger("WhatDataChanged");
            }
        }
        public string WhoChanged 
        {
            get => whoChanged;
            set
            {
                whoChanged = value;
                OnPropetryChanger("WhoChanged");
            }
        }
        public BankTable(string name, string surname, string otchestvo, string phone, string pasport)
        {
            Name = name;
            Surname = surname;
            Otchestvo = otchestvo;
            Phone = phone;
            Pasport = pasport;
        }
        public BankTable() { }

        public event PropertyChangedEventHandler PropertyChanged;       //событие динамического изменения свойств
        public void OnPropetryChanger([CallerMemberName] string prop = "")      //метод динамического изменения свойств
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(prop));
        }
    }
}
